---
title: "lab 2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# make sure some LaTeX reader is installed
# install.packages('tinytex')
# tinytex::install_tinytex()
library(tidyverse)
```


```{r warmup-vector-creation}
## warmup
a <- c(7:70)
b <- runif(60)
c <- rep('x', 1980)
angelou_quote <- c('Nothing','works','unless', 'you', 'do')
e <- rnorm(1000)
f <- seq(0,20,2)

# paste0(angelou_quote, collapse = ' ')
paste0(angelou_quote, collapse = emo::ji('clap'))

paste0(angelou_quote, ".com")
paste0(angelou_quote, c("!", "!", "?", " :(", "!!"))
  #paste0 takes two vectors and pastes the nth item of each vector together without spaces. 
```

``` {r mean-standard-deviation}
## IS THE COIN FAIR?
# create 10 coin flip samples with replacement
(coin_flips <- sample(c("Heads", "Tails"), 10, replace = TRUE))

# diagnose error
# die_rolls <- sample(c(1, 2, 3, 4, 5, 6), 100)
  # sampling without replacement, more samples than there are objects in the vector

# simulate 10, 1000, and 1000000 flips
set.seed(303)
ten_flips <- sample(c(1,0), 10, replace = T)
thousand_flips <- sample(c(1,0), 1000, replace = T)
million_flips <- sample(c(1,0), 1000000, replace = T)
#a - numeric
#b
sum(ten_flips) # 5 heads
sum(thousand_flips) # 482 heads
sum(million_flips) # 499948 heads
length(ten_flips) 
length(thousand_flips)
length(million_flips)
  # length indicates population or number of observations (flips) in vector

# calculate estimated probability 
n_heads <- sum(ten_flips)
n_flips <- length(ten_flips)
p_hat_ten <- n_heads/n_flips

n_heads_1k<- sum(thousand_flips)
n_flips_1k <- length(thousand_flips)
p_hat_1k <- n_heads_1k/n_flips_1k

n_heads_1m <- sum(million_flips)
n_flips_1m <- length(million_flips)
p_hat_1m <- n_heads_1m/n_flips_1m

# 5 simplify p hat with mean
p_hat_ten <- mean(ten_flips)
p_hat_1k <- mean(thousand_flips)
p_hat_1m <- mean(million_flips)
```

```{r}
# chi square sample by hand
set.seed(720)
x <- rchisq(10000, 3)

x_bar <- mean(x)
n <- length(x)

# sample variance & standard deviation
var_x<- sum(((x-x_bar)^2)/(n-1))
sd_x <- sqrt(var_x)

paste('did I calculate variance correctly?:',var(x) == var_x) # TRUE
paste('did I calculate standard deviation correctly?:',sd(x) == sd_x, '(',sd_x, ')') # TRUE

# tibble format

tibble(x = x) %>%
  summarize(mean = mean(x),
            variance = var(x),
            standard_deviation = sd(x)
            )

# swap summarize for mutate
tibble(x = x) %>%
  mutate(mean = mean(x),
            variance = var(x),
            standard_deviation = sd(x)
            )
  # each mutated filed is calculated on the whole vector x, repeated for each row
```

```{r challenge-problems}
# create samples
chi_sq_samples <-
  tibble(x = c(rchisq(100000, 1) + rchisq(100000, 1),
    rchisq(100000, 3),
    rchisq(100000, 4)),
    df = rep(c("2", "3", "4"), each = 1e5)
  )

# plot 
chi_sq_samples %>%
  ggplot(aes(x = x, group = df, fill =df)) +
    geom_density( alpha = .5) +
    labs(fill = "df", x = "sample")

# rows in tibble
dim(chi_sq_samples)[1]

# what happens when you delete each?
chi_sq_samples <-
  tibble(x = c(rchisq(100000, 1) + rchisq(100000, 1),
    rchisq(100000, 3),
    rchisq(100000, 4)),
    df = rep(c("2", "3", "4"), 1e5)
  )

chi_sq_samples %>%
  ggplot(aes(x = x, group = df, fill =df)) +
    geom_density( alpha = .5) +
    labs(fill = "df", x = "sample") +
  ggtitle(label = 'Chi-square distros - "EACH" ARGUMENT DELETED')

  # instead of repeating each object in the vector x times,  it 
```